- name: copiar tzupdater.jar
  copy:
    src: ./roles/tzdata/files/tzupdater.jar
    dest: /tmp/tzupdater.jar
    owner: root
    group: root
    mode: '0755'

- name: copiar tzdata2020d.tar.gz
  copy:
    src: ./roles/tzdata/files/tzdata2020d.tar.gz
    dest: /tmp/tzdata2020d.tar.gz
    owner: root
    group: root
    mode: '0755'

- name: Atualizar tzdata java
  shell: "cd /tmp/ && java -jar tzupdater.jar -l file:tzdata2020d.tar.gz -f "
  register: result
- debug: msg="{{ result.stdout }}"

- name: Checar hora java
  shell: "cd /tmp/ && java TesteHorario"
  register: result
- debug: msg="{{ result.stdout }}"