- name: copiar TesteHorario.class
  copy:
    src: ./roles/tzdata/files/TesteHorario.class
    dest: /tmp/TesteHorario.class
    owner: root
    group: root
    mode: '0755'

- name: copiar TesteHorario.java
  copy:
    src: ./roles/tzdata/files/TesteHorario.java
    dest: /tmp/TesteHorario.java
    owner: root
    group: root
    mode: '0755'

- name: Checar hora java
  shell: "cd /tmp/ && java TesteHorario"
  register: result
- debug: msg="{{ result.stdout }}"