- name: Deletar TesteHorario.class
  file:
    path: /tmp/TesteHorario.class
    state: absent

- name: Deletar TesteHorario.java
  file:
    path: /tmp/TesteHorario.java
    state: absent

- name: Deletar tzdata2020d.tar.gz
  file:
    path: /tmp/tzdata2020d.tar.gz
    state: absent

- name: Deletar tzupdater.jar
  file:
    path: /tmp/tzupdater.jar
    state: absent

- name: start  jboss
  command: "/etc/init.d/jboss stop"
  warn: no
  ignore_errors: yes
  register: result
- debug: msg="{{ result.stdout }}"

- name: start  jboss
  command: "/etc/init.d/jboss start"
  warn: no
  ignore_errors: yes
  register: result
- debug: msg="{{ result.stdout }}"