- name: Deletar TesteHorario.class
  file:
    path: /tmp/TesteHorario.class
    state: absent

- name: Deletar TesteHorario.java
  file:
    path: /tmp/TesteHorario.java
    state: absent

- name: Deletar tzdata2020d.tar.gz
  file:
    path: /tmp/tzdata2020d.tar.gz
    state: absent

- name: Deletar tzupdater.jar
  file:
    path: /tmp/tzupdater.jar
    state: absent

- name: stop jboss
  shell: /etc/init.d/jboss stop
  ignore_errors: yes
  register: result
- debug: msg="{{ result.stdout }}"

- name: killall java
  shell: killall -9 java
  ignore_errors: yes
  register: result
- debug: msg="{{ result.stdout }}"

- name: start  jboss
  shell: /etc/init.d/jboss start
  ignore_errors: yes
  register: result
- debug: msg="{{ result.stdout }}"